# scripts/finetune/action_seeds.py
"""Seed messages for each router action class used to bootstrap synthetic generation."""

from __future__ import annotations

ACTION_SEEDS: dict[str, list[dict[str, str]]] = {
    "answer_direct": [
        {"message": "What is compound interest?", "rag_context": ""},
        {"message": "Explain the difference between a stock and a bond.", "rag_context": ""},
        {"message": "What does ROI stand for?", "rag_context": ""},
        {"message": "How does inflation affect purchasing power?", "rag_context": ""},
        {"message": "What is a bear market?", "rag_context": ""},
        {"message": "Explain what a P/E ratio measures.", "rag_context": ""},
        {"message": "What is dollar-cost averaging?", "rag_context": ""},
        {"message": "How does short selling work?", "rag_context": ""},
        {"message": "What is a dividend yield?", "rag_context": ""},
        {"message": "What are the main asset classes?", "rag_context": ""},
        {"message": "What is diversification in investing?", "rag_context": ""},
        {"message": "Explain what a hedge fund does.", "rag_context": ""},
    ],
    "answer_from_rag": [
        {"message": "What does the document say about risk tolerance?", "rag_context": "financial planning PDF uploaded"},
        {"message": "Based on the report, what was Q3 revenue?", "rag_context": "quarterly earnings report uploaded"},
        {"message": "What are the key findings from the paper I shared?", "rag_context": "research paper on market volatility"},
        {"message": "Summarize the main points of the prospectus.", "rag_context": "fund prospectus uploaded"},
        {"message": "What does the uploaded policy say about margin calls?", "rag_context": "trading policy document"},
        {"message": "What is the investment thesis in this memo?", "rag_context": "investment memo uploaded"},
        {"message": "Does the report mention dividends?", "rag_context": "annual report uploaded"},
        {"message": "What risk factors does the filing highlight?", "rag_context": "SEC 10-K filing uploaded"},
        {"message": "Pull out the key metrics from the document.", "rag_context": "financial analysis report uploaded"},
        {"message": "What does this contract say about early termination?", "rag_context": "contract document uploaded"},
    ],
    "web_search": [
        {"message": "What is the latest news on the Fed interest rate decision?", "rag_context": ""},
        {"message": "What is the current inflation rate in the US?", "rag_context": ""},
        {"message": "Latest earnings report for Microsoft?", "rag_context": ""},
        {"message": "What are analysts saying about Tesla stock right now?", "rag_context": ""},
        {"message": "Has the ECB raised rates recently?", "rag_context": ""},
        {"message": "What is the current yield on 10-year US treasuries?", "rag_context": ""},
        {"message": "Recent news about the housing market?", "rag_context": ""},
        {"message": "What is the current unemployment rate?", "rag_context": ""},
        {"message": "Latest update on China's economy?", "rag_context": ""},
        {"message": "What did Warren Buffett say at the last Berkshire meeting?", "rag_context": ""},
        {"message": "Search for recent SEC actions against hedge funds.", "rag_context": ""},
        {"message": "What happened to SVB?", "rag_context": ""},
    ],
    "asset_price": [
        {"message": "What is Apple's stock price?", "rag_context": ""},
        {"message": "How is TSLA doing today?", "rag_context": ""},
        {"message": "Show me Bitcoin's current price.", "rag_context": ""},
        {"message": "What's the current price of NVDA?", "rag_context": ""},
        {"message": "Check the price for Amazon shares.", "rag_context": ""},
        {"message": "What is gold trading at right now?", "rag_context": ""},
        {"message": "Price of ETH please.", "rag_context": ""},
        {"message": "How much is Google per share?", "rag_context": ""},
        {"message": "Current MSFT quote?", "rag_context": ""},
        {"message": "Give me the price for JPM and GS.", "rag_context": ""},
        {"message": "What's SPY trading at?", "rag_context": ""},
        {"message": "How is META stock doing?", "rag_context": ""},
    ],
    "search_finance_tools": [
        {"message": "What is Apple's current P/E ratio?", "rag_context": ""},
        {"message": "Show me Netflix revenue growth over the last 5 years.", "rag_context": ""},
        {"message": "What is the debt-to-equity ratio for Tesla?", "rag_context": ""},
        {"message": "Give me the free cash flow for Microsoft.", "rag_context": ""},
        {"message": "What are the key financial ratios for NVDA?", "rag_context": ""},
        {"message": "Show me the income statement for Amazon.", "rag_context": ""},
        {"message": "What is the market cap of Apple vs Microsoft?", "rag_context": ""},
        {"message": "Find companies with dividend yield above 4%.", "rag_context": ""},
        {"message": "Best performing S&P 500 sectors this quarter?", "rag_context": ""},
        {"message": "Show me the balance sheet for JPMorgan.", "rag_context": ""},
    ],
    "ask_clarifying": [
        {"message": "Tell me about the market.", "rag_context": ""},
        {"message": "What should I invest in?", "rag_context": ""},
        {"message": "Help me with my portfolio.", "rag_context": ""},
        {"message": "Is it a good time?", "rag_context": ""},
        {"message": "I want to know more about stocks.", "rag_context": ""},
        {"message": "Tell me about Apple.", "rag_context": ""},
        {"message": "What about Tesla?", "rag_context": ""},
        {"message": "Should I buy or sell?", "rag_context": ""},
        {"message": "What's happening?", "rag_context": ""},
        {"message": "Can you help me?", "rag_context": ""},
        {"message": "What do you think about the market?", "rag_context": ""},
        {"message": "I need some advice.", "rag_context": ""},
    ],
}

ACTIONS: list[str] = list(ACTION_SEEDS.keys())
TARGET_PER_CLASS = 100
